web:
    build: web
    volumes:
        - /Users/marcof/Documents/CSE110M260T1/server/web:/code
    ports:
        - "5000:5000"
    links:
        - redis
    command: python app.py
redis:
    image: redis:2.8.19
    ports:
        - "6379:6379"
